#cloud-config
datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
  - name: keglia
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
    - ssh-rsa ******************************************
    - ssh-ed25519 **************************************
runcmd: []    
